package domaintree16

// !!!DON'T EDIT!!! Generated by infobloxopen/go-trees/etc from <name>tree{{.bits}} with etc -s uint16 -d uintX.yaml -t ./<name>tree\{\{.bits\}\}

import "github.com/infobloxopen/go-trees/domain"

type labelTree struct {
	root *node
}

type labelPair struct {
	Key   string
	Value *Node
}

type labelRawPair struct {
	Key   string
	Size  int
	Value *Node
}

func newLabelTree() *labelTree {
	return new(labelTree)
}

func (t *labelTree) insert(key string, value *Node) *labelTree {
	var (
		n *node
	)

	if t != nil {
		n = t.root
	}

	dl, size, _ := domain.MakeLabel(key)
	return &labelTree{root: n.insert(dl, size, value)}
}

func (t *labelTree) rawInsert(key string, size int, value *Node) *labelTree {
	var (
		n *node
	)

	if t != nil {
		n = t.root
	}

	return &labelTree{root: n.insert(key, size, value)}
}

func (t *labelTree) inplaceInsert(key string, value *Node) {
	dl, size, _ := domain.MakeLabel(key)
	t.root = t.root.inplaceInsert(dl, size, value)
}

func (t *labelTree) rawInplaceInsert(key string, size int, value *Node) {
	t.root = t.root.inplaceInsert(key, size, value)
}

func (t *labelTree) get(key string) (*Node, bool) {
	if t == nil {
		return nil, false
	}

	dl, size, _ := domain.MakeLabel(key)
	return t.root.get(dl, size)
}

func (t *labelTree) rawGet(key string, size int) (*Node, bool) {
	if t == nil {
		return nil, false
	}

	return t.root.get(key, size)
}

func (t *labelTree) enumerate() chan labelPair {
	ch := make(chan labelPair)

	go func() {
		defer close(ch)

		if t == nil {
			return
		}

		t.root.enumerate(ch)
	}()

	return ch
}

func (t *labelTree) rawEnumerate() chan labelRawPair {
	ch := make(chan labelRawPair)

	go func() {
		defer close(ch)

		if t == nil {
			return
		}

		t.root.rawEnumerate(ch)
	}()

	return ch
}

func (t *labelTree) del(key string) (*labelTree, bool) {
	if t == nil {
		return nil, false
	}

	dl, size, _ := domain.MakeLabel(key)
	if root, ok := t.root.del(dl, size); ok {
		return &labelTree{root: root}, true
	}

	return t, false
}

func (t *labelTree) rawDel(key string, size int) (*labelTree, bool) {
	if t == nil {
		return nil, false
	}

	if root, ok := t.root.del(key, size); ok {
		return &labelTree{root: root}, true
	}

	return t, false
}

func (t *labelTree) isEmpty() bool {
	return t == nil || t.root == nil
}

func (t *labelTree) dot() string {
	body := ""

	if t != nil {
		body = t.root.dot()
	}

	return "digraph d {\n" + body + "}\n"
}
